from django.contrib import admin
from polls.models import *

# admin.site.register(Question)
# admin.site.register(Choice)
# admin.site.register(TargetData)
# admin.site.register(AnnotationData)
admin.site.register(Text)
admin.site.register(Vocabulary)
admin.site.register(Person)
admin.site.register(TargetIndex)
admin.site.register(TargetData)
admin.site.register(Annotation)
admin.site.register(DirTargetindx)
admin.site.register(Directory)
admin.site.register(PersonDirectory)
admin.site.register(FinishCode)
admin.site.register(HaswellAns)
admin.site.register(DirNum)
admin.site.register(DirFinFlg)
admin.site.register(LimitNum)