# Generated by Django 2.1.1 on 2018-10-03 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnotationData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_num', models.IntegerField(default=-1)),
                ('cand_num', models.IntegerField(default=-1)),
                ('cand', models.CharField(max_length=20)),
                ('result', models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='TargetData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_num', models.IntegerField(default=-1)),
                ('text', models.CharField(max_length=200)),
                ('target', models.CharField(max_length=20)),
                ('target_index', models.IntegerField(default=-1)),
            ],
        ),
    ]
