# Generated by Django 2.1.1 on 2018-10-03 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_annotationdata_targetdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='annotationdata',
            old_name='cand',
            new_name='candidate',
        ),
    ]
