# Generated by Django 2.1.1 on 2018-10-03 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20181003_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotationdata',
            name='comment',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
