# Generated by Django 2.1.1 on 2018-10-03 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_annotationdata_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotationdata',
            name='target_num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.TargetData'),
        ),
    ]
