# Generated by Django 2.1.1 on 2018-10-03 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20181003_0912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotationdata',
            name='target_num',
        ),
    ]
