# Generated by Django 2.1.1 on 2018-10-04 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_annotationdata_target_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TargetIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='annotationdata',
            old_name='target_num',
            new_name='target_data',
        ),
        migrations.RemoveField(
            model_name='targetdata',
            name='target_num',
        ),
        migrations.AddField(
            model_name='targetindex',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Vocabulary'),
        ),
        migrations.AddField(
            model_name='targetindex',
            name='text',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Text'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate', to='polls.Vocabulary'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Person'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_word', to='polls.Vocabulary'),
        ),
    ]
