# Generated by Django 2.1.1 on 2018-10-04 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20181004_0427'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='comment',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
