# Generated by Django 2.1.1 on 2018-10-05 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_annotation_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='text',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.Text'),
            preserve_default=False,
        ),
    ]
