# Generated by Django 2.1.1 on 2018-10-10 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_annotation_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotationdata',
            name='target_data',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.RemoveField(
            model_name='annotation',
            name='candidate',
        ),
        migrations.RemoveField(
            model_name='annotation',
            name='target',
        ),
        migrations.RemoveField(
            model_name='annotation',
            name='text',
        ),
        migrations.RemoveField(
            model_name='targetdata',
            name='target',
        ),
        migrations.RemoveField(
            model_name='targetdata',
            name='text',
        ),
        migrations.AddField(
            model_name='annotation',
            name='target_data',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='polls.TargetData'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='targetdata',
            name='candidate',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='polls.Vocabulary'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='targetdata',
            name='target_index',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.TargetIndex'),
        ),
        migrations.AlterField(
            model_name='targetindex',
            name='index',
            field=models.IntegerField(default=-1),
        ),
        migrations.DeleteModel(
            name='AnnotationData',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
