# Generated by Django 2.1.1 on 2018-10-24 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_auto_20181010_0353'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirTargetindx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dir_name', models.CharField(max_length=20)),
                ('target_index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Vocabulary')),
            ],
        ),
    ]
