# Generated by Django 2.1.1 on 2018-10-24 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_auto_20181024_0419'),
    ]

    operations = [
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dir_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='dirtargetindx',
            name='dir_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Directory'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='dir_name',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, to='polls.Directory'),
            preserve_default=False,
        ),
    ]
