# Generated by Django 2.1.1 on 2018-10-31 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_finishcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persondirectory',
            old_name='come_num',
            new_name='dir_num',
        ),
    ]
