# Generated by Django 2.1.1 on 2018-11-06 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_auto_20181031_0546'),
    ]

    operations = [
        migrations.CreateModel(
            name='HaswellAns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gold_result', models.IntegerField()),
                ('target_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.TargetData')),
            ],
        ),
    ]
